name: Build and Deploy Angular App to AWS S3

on:
  push:
    branches:
      - frontend-dev
defaults:
  run:
    working-directory: exercise1/stargate-frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm ci

    - name: Build Angular app
      run: npm run build --prod

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: build-output
        path: dist/stargate-frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4.1.8
      with:
        name: build-output

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Sync S3 Bucket
      run: |
        aws s3 sync dist/stargate-frontend s3://acts-front --delete

    - name: Invalidate CloudFront distribution
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
