name: Build and Push Docker .NET Image to AWS ECR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: exercise1/api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build for Linux x64
      run: dotnet publish -c Release -r linux-x64 --self-contained --output ./publish

    - name: Zip deployment package
      run: zip -r deploy.zip ./publish
    - name: Deploy to EB
      uses: davecarlson/beanstalk-deploy@v23
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: BamtechBackend
        environment_name: BamtechBackend-env
        version_label: 12345
        region: us-west-1
        deployment_package: deploy.zip


